version: "3.8"
services:
    appserver:
        build:
            context: ./app
        ports:
            - "3000:8080"
    nginxproxy:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"